[project]
name = "followservice"
version = "0.1.0"
description = ""
authors = [
    {name = "Nokotachi",email = "none@none.none"}
]
readme = "README.md"
requires-python = "=3.12.7"
dependencies = [
    "fastapi[all] (>=0.121.2,<0.122.0)",
    "neo4j (>=6.1.0,<7.0.0)",
    "asyncio (>=4.0.0,<5.0.0)",
    "aio-pika (>=9.6.1,<10.0.0)",
]

[tool.poetry]
packages = [{include = "followservice", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
