"""создание таблицы user

Revision ID: 2e88f509dc4f
Revises: 
Create Date: 2025-11-02 00:03:02.720830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '2e88f509dc4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('followed', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('card_image1', sa.String(), nullable=True),
    sa.Column('card_image2', sa.String(), nullable=True),
    sa.Column('collections', sa.String(), nullable=True),
    sa.Column('verificated', sa.Boolean(), nullable=True),
    sa.Column('vector_of_interest', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('self_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('Trust', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
